### PR TITLE
solved

### PR DESCRIPTION
**Pull request by Omar-Ali99**

### CODE REVIEW

**Comment by wijdan-alharbi** [comment]
Well done Omar.  i hope you read the requirements carefully next time, you must have a real estate website. also, you forgot to add the google fonts icon.

**Comment by Omar-Ali99** [comment]
sorry about the real estate, I thought everyone does what he wanted , I'll update it with google icon and re-upload the lab

**Comment by Omar-Ali99** [comment]
the lab has been re uploaded with google icon

**Comment by wijdan-alharbi** [comment]
thank you.

**Pull request closed without merging**
